### ISSUE TITLE
Getting an RAI

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#10]
Do you think it would be also useful to be able to get an 4D RAI if, e.g., the file happens to contain a movie? Or do you think one should always return a `Source` and then one could construct a 4D RAI using the `source.getSource( t , level )`?  Maybe the latter is more generic and, if everything is done lazily, would also have no memory and computational overhead.

**Comment by NicoKiaru** [comment]
I think it's better with source handling the time -> thus it's compatible with bdv xml datasets (and missing views).

Not sure I tested timelapse thoroughly. Is it working, for instance with the cell division sample 5D dataset ?
