### ISSUE TITLE
Volatile vs. NonVolatile

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#12]
somehow, at this stage one in fact does seem to have access to both the volatile and non-volatile versions of the data:
- https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BFViewerImgLoader.java#L30

Frankly, I find all of this Volatile vs. nonVolatile quite confusing :-)
I would probably need to sit together with Tobias for one afternoon to get this properly e explained.

**Comment by NicoKiaru** [comment]
currently the volatile display is handled correctly by using spimdata conversion beforehand

if one want to take the source instead, then hte choice between volatile or not should be done in this repo, while waiting for a potential PR in BdvFunctions:

https://github.com/bigdataviewer/bigdataviewer-vistools/pull/38

If BdvFunctions wraps it itself into a volatile version, then the volatile stuff in this repo is superfluous and can be removed.
