### ISSUE TITLE
Separating Commands from Normal Classes

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#13]
Hi Nico,

I pulled the latest version and for my taste there could be still a better separation of SciJava specific Command logic and normal Java code. For example, there are lines of code like this:
```
final AbstractSpimData asd = (AbstractSpimData) cs.run(BioFormatsConvertFilesToSpimData.class, true,predefinedParameters).get().getOutput("asd");
```
I suspect that people that do not use SciJava will have a hard time using this code.
Personally I would do it like this:

I would have one folder (package name) with all the commands, e.g.:

`ch/epfl/biop/bdv/bioformats/command`

In there, I would have, e.g. 

`BioFormatsConvertFilesToSpimDataCommand`

with all the `@Parameter` stuff.

`BioFormatsConvertFilesToSpimDataCommand` would only have this method:

```
BioFormatsConvertFilesToSpimDataCommand.run()
{
   parameters = fetchParameters();
   BioFormatsConvertFilesToSpimData  converter = new BioFormatsConvertFilesToSpimData( parameters );
   SpimData spimData = converter.openAsSpimData( file );
    
   if ( advancedView )
   {
      MetaData metaData = converter.readMetaData( file );
      BdvFunctions2.show( spimData, metaData ); /// in there you could do all the additional stuff with the colours and grouping a.s.o , i.e. use all the metaData that we currently cannot put into SpimData 
   }
   else
   { 
      BdvFunctions.show( spimData );
   }

}
```

I think this would make it easier to use and understand. What do you think?
Frankly, at least for me to be useable it probably would have to look somehow like this ;-)

**Comment by tischi** [comment]
...and for the `parameters` I am not sure what it most convenient here. As I said, for me it works well to have a separate class `Settings` class, but maybe a `builder` pattern is better. Personally I find a `Map< String, Object > map` not so cool, because as a user one has to somehow figure out which Strings are allowed and also the code the consumes the map has to do all the type casting, which I personally find annoying. I thought you said you implemented a builder pattern already somewhere? I could not find it.

**Comment by NicoKiaru** [comment]
I do not know if it's a 'textbook' builder pattern, but here it is:

https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java

You have functions which map to the way sources are opened.

Another advantage of this class is that all parameters are serializable. This allows to easily write and read such a class, automatically. You'll find the code for this here:
* writing:

https://github.com/BIOP/bigdataviewer-bioformats/blob/591daacffb377dd2e5dc64dbab74dd489bb944d2/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/XmlIoBioFormatsImgLoader.java#L35

* reading:

https://github.com/BIOP/bigdataviewer-bioformats/blob/591daacffb377dd2e5dc64dbab74dd489bb944d2/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/XmlIoBioFormatsImgLoader.java#L57

It's also wrote as string, so perfectly understandable and modifiable from the xml file.

cf your other issue

And thanks for looking at it so carefully!

**Comment by NicoKiaru** [comment]
For the logic and the way to implement I agree it's not the way. Originally I wanted to remove everything related to display. But clearly this makes it so hard to use without it that we need at least a bit of proper display function. And a better separation from scijava to function logic is fine, but let's keep the bare minimum commands in the repo:
* A command to build a dataset from several files
* A command to show several files, with or without proper display handling
* a third useful one ?

Do you want to give it a shot or I can try to implement your idea in the first post ?

**Comment by NicoKiaru** [comment]
Hum ok so I really need this metadata information... 
I work now on something like what you suggested.

**Comment by tischi** [comment]
I would actually **keep all the commands** in the repo, but in the way I suggested above.
...and I am gone now for a few days. I could work on it a bit middle next week.

**Comment by NicoKiaru** [comment]
Done in commit https://github.com/BIOP/bigdataviewer-bioformats/commit/09d239dc4bb1581ff6b9f31ddcb24136edb34700
