### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#14]
Another thing I find not ideal is code like this:

```
            predefinedParameters.put("xmlFilePath", new File(files[0].getParent()));
            predefinedParameters.put("useBioFormatsCacheBlockSize", true);
            predefinedParameters.put("xmlFileName", "dataset.xml");
            predefinedParameters.put("positionIsCenter", "AUTO");
            predefinedParameters.put("cacheSizeX", 0);
            predefinedParameters.put("cacheSizeY", 0);
            predefinedParameters.put("cacheSizeZ", 0);
            predefinedParameters.put("saveDataset", false);
            predefinedParameters.put("switchZandC", "AUTO");
            predefinedParameters.put("flipPosition", "AUTO");
            predefinedParameters.put("verbose", false);
            predefinedParameters.put("refFramePositionValue", 1);
            predefinedParameters.put("refFrameVoxSizeValue", 1);
            predefinedParameters.put("cacheSizeX", 512);
            predefinedParameters.put("cacheSizeY", 512);
            predefinedParameters.put("cacheSizeZ", 1);
        }
```

If someone wants to use this, how do they know which Strings they are allowed to put there?

If you really want to use a Command as normal code, which as said in the other issue I would avoid, you can at least do it like this:

```
BioFormatsConvertFilesToSpimDataCommand converter  = new BioFormatsConvertFilesToSpimDataCommand();
converter.xmlFilePath = new File(files[0].getParent());
converter.useBioFormatsCacheBlockSize = true;
...
convert.run();
```

That has several advantages:
1. It looks like normal Java code
1. You do not need the CommandService
1. You do not have to worry to type the parameter names correctly, because your IDE will auto-complete for you.

**Comment by NicoKiaru** [comment]
Yeah I agree, it's not ideal but it's the choice between an automated ui and convenience for code writing. There's no ideal option

Currently, what this allows is to popup a second window with advanced parameters in case the user check `advancedParameters`. However:
* It's not convenient for code writing as you noticed
* The advanced parameters are not scriptable, when launching the command programmatically

**Comment by NicoKiaru** [comment]
predefinedparams sort of code removed in all except the examples in test packages

see commit https://github.com/BIOP/bigdataviewer-bioformats/commit/09d239dc4bb1581ff6b9f31ddcb24136edb34700
