### ISSUE TITLE
BioFormats limitations

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#15]
I guess there should be somewhere code to handle the current short-comings of Bio-Formats?!
Something where you do file-type (e.g. Nikon) specific things?
Could you point me to that code?

**Comment by NicoKiaru** [comment]
Sure, so the logic is located in the class `BioFormatsBdvOpener`

Basically, to get sources one way is to write something like that:
```
		List<Source> sources =
				BioFormatsBdvOpener.getOpener()
                                                .location("myfile.tif")
						.cornerPositionConvention()
						.millimeter() // unit = millimeter
						.positionReferenceFrameLength(new Length(1, UNITS.MICROMETER)) // sets the length of the reference frame for stage position, if used by bioformats in the reader
						.voxSizeReferenceFrameLength(new Length(100, UNITS.MICROMETER))
// sets the length of the reference frame for voxel size, if used by bioformats in the reader
						.getVolatileSources()
						.stream().map(src -> (Source) src).collect(Collectors.toList());
```

Now the class `BioFormatsBdvOpener` contains several methods which change the way the sources are opened (units, center/corner convention, split rgb, cache size etc.).

It's also containing a function `.auto()` where you it will autoset some opening parameters based on the file format notably. It's located here:

https://github.com/BIOP/bigdataviewer-bioformats/blob/591daacffb377dd2e5dc64dbab74dd489bb944d2/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L109-L141

Currently it contains the proper settings for nd2 Nikon setting, but it can be modified with extra stuff when needed (it's also easy to remove if bioformats improves and standardize more stuff).

Also this  `BioFormatsBdvOpener`  is used internally when building an `abstractspimdata` object. So there is no duplicated code.

**Comment by tischi** [comment]
Awesome!
That class looks really good to me.

**Comment by tischi** [comment]
But could we separate out everything that would be along the lines of "writing our own BioFormats" on top? If that is somewhere clearly separated it would be easier to ship the information that we accumulate to the BioFormats guys.

**Comment by NicoKiaru** [comment]
> But could we separate out everything that would be along the lines of "writing our own BioFormats" on top?

How would you do that ? Currently, we can, if we write the serialized opener file (by exporting into a xml dataset file), have a quick overview of the modifications we had to implement in order for the file to open correctly:

Example for the nd2 files:
```
      <opener_0>{"dataLocation":"C:\\Users\\chiarutt\\CachedSamples\\NicoKiaru\\TestImages\\raw\\master\\ND2\\20x_g5_a1.nd2","useBioFormatsXYBlockSize":true,"cacheBlockSize":{"min":[0,0,0],"max":[512,512,1],"n":3},"swZC":false,"splitRGBChannels":false,"u":{"measurementSystem":"SI.METRE","symbol":"µm","scaleFactor":1.0E-6,"offset":0.0},"positionPreTransformMatrixArray":[-1.0,-0.0,-0.0,-0.0,-0.0,-1.0,-0.0,-0.0,-0.0,-0.0,-1.0,-0.0],"positionReferenceFrameLength":{"value":1.0,"unit":{"measurementSystem":"SI.METRE","symbol":"µm","scaleFactor":1.0E-6,"offset":0.0},"hashCodeValue":-469615208},"positionIgnoreBioFormatsMetaData":true,"positionIsImageCenter":true,"voxSizeReferenceFrameLength":{"value":1.0,"unit":{"measurementSystem":"SI.METRE","symbol":"µm","scaleFactor":1.0E-6,"offset":0.0},"hashCodeValue":-469615208},"voxSizeIgnoreBioFormatsMetaData":true,"axesOfImageFlip":[false,false,false],"nFetcherThread":2,"numPriorities":4}</opener_0>
```

Step by step:
* "axesOfImageFlip":[false,false,false] -> no flip
* "positionIsImageCenter":true ->position is center
* "positionReferenceFrameLength":blabla ->I had to define a reference frame in physical size
* "swZC":false -> no switch between Z and C

I don't know if the issues we find are 'standard' enough to require extra splitting of the code. How would you do that? I feel like notifying the bioformats people with clear issue could be enough.

So far what we've identified:
* center/corner
* reference frame -> what is it ?
* should the stage position be flipped ?
* should the image be flipped ?

**Comment by NicoKiaru** [comment]
In the commit

The opener class calls fix based on file formats:

https://github.com/BIOP/bigdataviewer-bioformats/blob/bee09b743e48130bdfca690bbc504112c52960d9/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L221-L228

The class  `BioFormatsBdvOpenerFix`  contains all potential file format specific fix

These are the two locations to handle such fix, it should be hopefully pretty straightforward to remove or add stuff based on our needs and on how BioFormats changes formats handling
