### ISSUE TITLE
Calling commands from code

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#2]
```
Future<CommandModule> module = cs.run(BioFormatsOpenPlugInSingleSourceSciJava.class, false,
                                    "sourceIndex", p.getLeft(),
                                    "channelIndex", idCh,
                                    "bdv_h", bdv_h,
                                    "createNewWindow", createNewWindow,
                                    "inputFile", inputFile,
                                    "switchZandC", switchZandC,
                                    "autoscale", autoscale,
                                    "appendMode", appendMode,
                                    "keepBdv3d", keepBdv3d,
                                    "cacheBlockSizeX", cacheBlockSizeX,
                                    "cacheBlockSizeY", cacheBlockSizeY,
                                    "cacheBlockSizeZ", cacheBlockSizeZ,
                                    "letBioFormatDecideCacheBlockXY", letBioFormatDecideCacheBlockXY,
                                    "ignoreMetadata", ignoreMetadata,
                                    "unit", unit

                            );
                            cm = module.get();
```

Is there a reason why to not call it simply like this?
```
final BioFormatsOpenPlugInSingleSourceSciJava command = new BioFormatsOpenPlugInSingleSourceSciJava();
command.bdv_h = bdv_h;
// ...
command.run();
```

**Comment by tischi** [comment]
An issue with the current approach is that one needs a `CommandService` from somewhere, which not every user might know how to construct...

**Comment by NicoKiaru** [comment]
Agreed, it needs SciJava's magic. One may want to remove this dependency, and make a logic separated between displaying and getting the sources. I'm not sure it's the priority at this point. One thing which is completely omitted is this cachecontrol story (see loader).  I need to open an issue. I would say it's the main issue at the moment.

**Comment by NicoKiaru** [comment]
> Is there a reason why to not call it simply like this?
> 
> ```
> final BioFormatsOpenPlugInSingleSourceSciJava command = new BioFormatsOpenPlugInSingleSourceSciJava();
> command.bdv_h = bdv_h;
> // ...
> command.run();
> ```

You can, as noted in your example : 

https://github.com/tischi/bigdataviewer-bioformats/blob/master/src/test/java/explore/ExploreOpeningImages.java#L12

It can be done because all fields are public, and I think also because you are starting an ImageJ instance, which enables the automatic scijava injection. Not sure about the second part however.

**Comment by NicoKiaru** [comment]
mostly obsolete I believe. Please Reopen it in case I missed something
