### ISSUE TITLE
Add Filename to progress logging

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#23]
@NicoKiaru 
Could we add the filename to such messages?
`Attempts to set opener settings for file format Zeiss CZI`

**Comment by NicoKiaru** [comment]
Yes it's here:

https://github.com/BIOP/bigdataviewer-bioformats/blob/ab0df75c563e0894aef78979f23d4469fd8b5c4f/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L278

Just add the `dataLocation` field (it's not a necessarily a file but dataLocation contains the file path it is a file.

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/bigdataviewer-bioformats/commit/c9ca56b7a9fc7b19b50cd35c4a4af2d9dc2e3526
