### ISSUE TITLE
Display 2D images in BDV

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#25]
@NicoKiaru 
Regarding the discussion in gitter.
What do you recommend to display a bunch of 2D sources opened with bdv-bioformats in bdv?
The issue is that they can have slightly different z-offsets due to the acquisition protocol.
It looks like I need to force them at some point to all have the same (even better zero) offset.
Any suggestions of how to best achieve this? Wrap all into `TransformedSource`s that nullify the respective offsets?

**Comment by NicoKiaru** [comment]
Th alternative cheating way is to set a huge `ReferenceFrameLength` size. If it's bigger than any z offset, the image will show up.

https://github.com/BIOP/bigdataviewer-bioformats/blob/ab0df75c563e0894aef78979f23d4469fd8b5c4f/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L154

**Comment by NicoKiaru** [comment]
Rather this one:

https://github.com/BIOP/bigdataviewer-bioformats/blob/ab0df75c563e0894aef78979f23d4469fd8b5c4f/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L170

**Comment by tischi** [comment]
Makes sense! This is in fact a trick that I used already (not with bdv-bioformats) when I wanted to show 2D sources together with 3D sources and wanted the 2D sources to be visible along the whole z-axis.
I think I will go for this!

**Comment by tischi** [comment]
But I **_only_** want to extend the source along the z dimension!

```
@Parameter(
        required = false,
        label = "Reference frame size in unit (voxel size)"
    )
    public double refFrameSizeInUnitVoxSize = 1.0D;
```

This reads as if this would set the size in all dimensions?

**Comment by tischi** [comment]
...and what about this guy?
```
@Parameter(required = false, label="Reference frame size in unit (position)")
    public double refFrameSizeInUnitLocation = 1;
```
Shouldn't I put it to some negative value such that the source also spans across `z = 0`?

**Comment by tischi** [comment]
I don't get it to work....
When looking at the sourceTransform it looks like that no matter what I set:

```
3d-affine: (0.25074568288853993, 0.0, 0.0, 21865.139, 0.0, 0.25074568288853993, 0.0, 21759.865, 0.0, 0.0, 1.0, 2350.73)
```
I think what I need is the `1.0` at the second last entry to become very big, but it does not change, even if I set:
```
bridgeCommand.refFrameSizeInUnitVoxSize = 500.0D;
bridgeCommand.refFrameSizeInUnitLocation = - bridgeCommand.refFrameSizeInUnitVoxSize / 2.0;
```

I debugged into it and it is here:

```
BioFormatsMetaDataHelper

public static VoxelDimensions getSeriesVoxelDimensions(IMetadata omeMeta, int iSerie, Unit u, Length voxSizeReferenceFrameLength) {
        // Always 3 to allow for big stitcher compatibility
        //int numDimensions = 2 + (omeMeta.getPixelsSizeZ(iSerie).getNumberValue().intValue()>1?1:0);
        int numDimensions = 3;
        Length[] voxSize = getSeriesVoxelSizeAsLengths(omeMeta, iSerie);
        double[] d = new double[3];

        for (int iDimension = 0; iDimension<3;iDimension++) { // X:0; Y:1; Z:2
            if ((voxSize[iDimension].unit()!=null)&&(voxSize[iDimension].unit().isConvertible(u))) {
                d[iDimension] = voxSize[iDimension].value(u).doubleValue();
            } else if (voxSize[iDimension].unit().getSymbol().equals("reference frame"))  {
                Length l = new Length(voxSize[iDimension].value().doubleValue() * voxSizeReferenceFrameLength.value().doubleValue(), voxSizeReferenceFrameLength.unit());
                d[iDimension] = l.value(u).doubleValue();
            } else {
                d[iDimension] = 1;
            }
        }
```

it only applies it

`if( voxSize[iDimension].unit().getSymbol().equals("reference frame") )`

which is not the case for me and also it applies it for all dimensions, not sure that's what we need?

**Comment by tischi** [comment]
@NicoKiaru 
Do you have a function to get the whole time range of a source?
I guess we would need this to initiate a `SourceAndConverterAndTimeRange` such that the whole time range is covered?

**Comment by NicoKiaru** [comment]
ahahah.

No ;-(

I feared this moment would happen. I don't really know a good way to do this. Maybe we could store it in the sourceandconverter metadata when the spimdata is being opened ?

**Comment by tischi** [comment]
> Maybe we could store it in the sourceandconverter metadata when the spimdata is being opened

Sounds like a good option. It is a bit weird to me that the Source itself does not know it, but I think there must have been a reason why Tobias et al. designed this.

**Comment by NicoKiaru** [comment]
Sometimes there are missing views. Missing views are also stored into the AbstractSpimData object. Maybe sometimes you want to have negative values ? Anyway in `Source` you only have the `isPresent(t)` method, so it's not aware of the range covered by the timepoint

**Comment by NicoKiaru** [comment]
There are two issues in one thread : the time and the z extension.

Regarding z extension : any news @tischi ?

For the time range, I think it's an issue more general than bioformats. We could make a static helper function in bdv-playground.

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
