### ISSUE TITLE
Many threads

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#26]
@NicoKiaru 
I am opening many (~100) images and when looking with VisualVM there are many (>>100) fetcherThreads created.
This is without showing the sources in Bdv.

![image](https://user-images.githubusercontent.com/2157566/98265792-ccb00380-1f89-11eb-8b46-3fecee493026.png)

Do you think this is normal? Or maybe some issue?

**Comment by NicoKiaru** [comment]
Many threads is ok I believe. There are two threads per files.

**Comment by tischi** [comment]
ok! what's their purpose? Will they become active later?

![image](https://user-images.githubusercontent.com/2157566/98266578-c706ed80-1f8a-11eb-8a0a-d8974c593d3b.png)

**Comment by NicoKiaru** [comment]
These threads are initialised and are parameters of the `SharedQueue` instantiated here

https://github.com/BIOP/bigdataviewer-bioformats/blob/ca05c9247ea5efd3a6a57dbfdef1fc47b81d5061/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BioFormatsImageLoader.java#L85

Then it's used here:

https://github.com/BIOP/bigdataviewer-bioformats/blob/ca05c9247ea5efd3a6a57dbfdef1fc47b81d5061/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BioFormatsImageLoader.java#L87

But to be honest, I'm not sure what they are for. I guess they are fetching the cells in CellLoader ?

**Comment by NicoKiaru** [comment]
I'm closing this. I think it's a normal behaviour. Please reopen if you notice some issues linked to it
