### ISSUE TITLE
Bioformats ImageReader takes too much RAM for small images

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#27]
@NicoKiaru 
```
		AbstractSpimData< ? > spimData = BioFormatsConvertFilesToSpimData.getSpimData( opener );
		List< ConverterSetup > converterSetups = new ArrayList<>();
		List< SourceAndConverter< ? > > sourceAndConverters = new ArrayList<>();
                // below line causes oom:
		BigDataViewer.initSetups( spimData, converterSetups, sourceAndConverters );
```
Above code runs in a loop.
If I only execute the first line it is fine, but the `initSetups` allocates about 6 times the amount of memory.
Do you think this is normal?

**Comment by NicoKiaru** [comment]
Could be. Not sure. How much memory is that ?

**Comment by tischi** [comment]
`1 GB => 7 GB`
Ok, but curious...

**Comment by NicoKiaru** [comment]
Is it with the images you gave me ? WIth just the czi files, I get 2.5 Gb usage

**Comment by NicoKiaru** [comment]
That's still crazy and way too high : there are 68 files of 5 Mb. Pretty far from 2.5 Gb

**Comment by NicoKiaru** [comment]
Ok, it looks like the CZIReader creates a ton (a ton) of Strings. 

There are 1.1Gb used in Strings being held by ZeissCZIReader instances:

![image](https://user-images.githubusercontent.com/20223054/98285913-7ea7f980-1fa3-11eb-991c-aa32eba95906.png)

This is probably why it's both slow to open and why it's so huge in memory...

**Comment by NicoKiaru** [comment]
That's crazy.

**Comment by tischi** [comment]
> Is it with the images you gave me ? WIth just the czi files, I get 2.5 Gb usage

It was with all the image files, including the .ome.tif, you could try how it is with opening them as well.

> There are 1.1Gb used in Strings being held by ZeissCZIReader instances:

That really is crazy, but cool you found it!
Maybe ask the bio-formats developers? 
Or, maybe, in fact someone from Zeiss?
...depending on who wrote the code.

**Comment by tischi** [comment]
@NicoKiaru 
Should we post in the forum?
I could do it, but I think you are more into the technicalities.
I could also start the thread and then you could amend.

**Comment by NicoKiaru** [comment]
I need to check a bit more.

**Comment by tischi** [comment]
@NicoKiaru 
Did you have the chance to look into this more?

**Comment by NicoKiaru** [comment]
Sorry, no and I won't have time. Sorry for the useless delay, It's probably better to put this in the forum

**Comment by tischi** [comment]
@NicoKiaru 
Could you answer this question?
https://forum.image.sc/t/open-czi-in-bio-formats-large-ram-requirements/45592/2
I am not sure whether you are using "the same reader"...

**Comment by tischi** [comment]
@NicoKiaru 
Did you see this?
https://forum.image.sc/t/open-czi-in-bio-formats-large-ram-requirements/45592/4

**Comment by NicoKiaru** [comment]
Interesting, we could think of getting the metadata we need with a first "full" reader and then reopening the file with a "minimum" reader just for accessing the data

**Comment by tischi** [comment]
> Interesting, we could think of getting the metadata we need with a first "full" reader and then reopening the file with a "minimum" reader just for accessing the data

Yes, that sounds good!

**Comment by NicoKiaru** [comment]
Wrote here for the record (from @dgault):

> Though as a possible easy solution, if the original metadata is not required then you can prevent it from being populated using reader.setOriginalMetadataPopulated(false); That could potentially reduce the size of metadata substantially.

I think the only places where a reader is created is 

https://github.com/BIOP/bigdataviewer-bioformats/blob/41abef939172d14e3d27b26463a07096b22cec47/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L266

and 

https://github.com/BIOP/bigdataviewer-bioformats/blob/41abef939172d14e3d27b26463a07096b22cec47/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L363

We could create a function `getNewReaderWithMetadata` and `getNewReaderNoMetadata` but it needs a bit more digging to know when to call one or the other

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
