### ISSUE TITLE
Benchmarking of `initSetups`

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#28]
@NicoKiaru 
Running `BigDataViewer.initSetups` also is quite slow.
Maybe this helps to see where it spends most of the time?
![image](https://user-images.githubusercontent.com/2157566/98272696-a7bf8e80-1f91-11eb-96fb-923986029cc7.png)
It looks like it is the `getMipMapTransform()` function of the `BioFormatsSetupLoader`.
Is there something to be done to improve the performance?
I don't know, maybe we have this information already when instantiating the `AbstractSpimData` and could cache it there?

**Comment by tischi** [comment]
...here one can also see that `getSpimData()` is comparatively fast:

![image](https://user-images.githubusercontent.com/2157566/98273290-624f9100-1f92-11eb-9d10-bc8d268c2818.png)

**Comment by tischi** [comment]
you have tons of calls like this:

`concreteSource.getNumMipmapLevels()`

which each time executes this code:

```
    public int getNumMipmapLevels() {
        int numMipMapLevels = -1;
        try {
            IFormatReader reader = readerPool.acquire();
            reader.setSeries(cSerie);
            numMipMapLevels = reader.getResolutionCount();
            readerPool.recycle(reader);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return numMipMapLevels;
    }

```

I assume that the actual reading from the file could be done **only once** and the `numMipMapLevels` stored (i.e., lazy initialisation)?!

1. Would you agree?
2. Do you want me to make a PR or do you want to have a look yourself?

**Comment by tischi** [comment]
Same here:
```
/**
     * Finds transform based on the root transform (highest resolution transform)
     * And assuming all resolution level cover the same area of imaging
     * @param t
     * @param level
     * @param transform
     */
    @Override
    public void getSourceTransform(int t, int level, AffineTransform3D transform) {
        // Ignoring t parameters : assuming all transforms are identical over time
        // TODO How is the pyramid in 3D ?
        level = levelCropper(level);
        if (!transforms.contains(level)) {
            if (level==0) {
                transforms.put(0, this.rootTransform);
            } else {
                AffineTransform3D tr = new AffineTransform3D();
                tr.set(rootTransform);

                // Apply ratio in numbers of pixel
                long nPixXLvl0 = 0;
                long nPixYLvl0 = 0;
                long nPixZLvl0 = 0;
                try {
                    IFormatReader reader = readerPool.acquire();
                    reader.setSeries(cSerie);
                    reader.setResolution(0);
                    nPixXLvl0 = reader.getSizeX();
                    nPixYLvl0 = reader.getSizeY();
                    nPixZLvl0 = reader.getSizeZ();
                    readerPool.recycle(reader);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                long nPixXCurrentLvl = this.getSource(t,level).dimension(0);

                long nPixYCurrentLvl = this.getSource(t,level).dimension(1);

                long nPixZCurrentLvl = this.getSource(t,level).dimension(2);

                tr.translate(-pXmm, -pYmm, -pZmm);

                tr.set(tr.get(0,0)*((double)nPixXLvl0/(double)nPixXCurrentLvl),0,0);
                tr.set(tr.get(1,1)*((double)nPixYLvl0/(double)nPixYCurrentLvl),1,1);
                tr.set(tr.get(2,2)*((double)nPixZLvl0/(double)nPixZCurrentLvl),2,2);

                tr.translate(pXmm, pYmm, pZmm);
                transforms.put(level, tr);
            }
        }

        transform.set(transforms.get(level));
    }
```

**Comment by NicoKiaru** [comment]
Are you sure the getNumMipmapLevels is called a lot of times ?

But if yes, we can cache, but I would cache it directly in the class holding getNumMipmapLevels after a first call. But one has to be sure it's a performance issue. I don't really understand your screenshot with the ms. But yes try to cache it and see if it solves your issue.

**Comment by tischi** [comment]
> Are you sure the getNumMipmapLevels is called a lot of times ?

yes, many times.

It's much faster now with the caching. I also added caching at another place, but I think this did not help as the method was likely only called once (you will see in the PR).

Right now the slowest part of the code is this:

![image](https://user-images.githubusercontent.com/2157566/98279580-667fac80-1f9a-11eb-9595-5d98eb693643.png)

But I don't know if one can do something about it.

**Comment by NicoKiaru** [comment]
Cool! Not sure the other stuff can be sped up indeed. It should be negligible compared to the time being actually spend loading data I guess

**Comment by tischi** [comment]
Yes, but one has to wait ~20 seconds before one can see anything.
Humans short term attention span is ~5 seconds, after that one gets nervous ;-)
So, if we can still improve it would be nice.

**Comment by NicoKiaru** [comment]
What sort of data do you look at ? I've never experienced this. If you have plenty of individual tiff, this can be a limitation of the BIoformats API itself and then there's nothing we can do about it. Is there an autoscaling ? Can you share a sample problematic dataset ?

**Comment by tischi** [comment]
It's many 2D czi files. 
I'll send you a mail.

**Comment by NicoKiaru** [comment]
@tischi can you comment on this issue ? Is there still a performance issue ?

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
