### ISSUE TITLE
.bfmemo

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#29]
@joshmoore
Do you know whether one can tell BioFormats (Java API) not to create the `*.bfmemo` files?
@NicoKiaru
Using bdv-bf it is creating those files (one per image). May be good to have them, but I wonder whether it is a performance issue for us, so I would like to test what happens if we don't create them.

**Comment by NicoKiaru** [comment]
I used memoization by default in bdv-bioformats. Turns out we have datasets which are heavy to parse. Why do you want to disable it ?

Which file format do you use ?

**Comment by tischi** [comment]
I sent you the czi files by mail.

I open all of them in a for loop using this code:

```
public class SourceAndConverterOpener
{
	private OpenFilesWithBigdataviewerBioformatsBridgeCommand bridgeCommand;

	public SourceAndConverterOpener()
	{
		DebugTools.setRootLevel("OFF");
		bridgeCommand = new OpenFilesWithBigdataviewerBioformatsBridgeCommand();
		bridgeCommand.useBioFormatsCacheBlockSize = true;
		bridgeCommand.unit = "MICROMETER";
	}

	public List< SourceAndConverter< ? > > open( final String imagePath, boolean is2D )
	{
		BioFormatsBdvOpener opener = bridgeCommand.getOpener( new File( imagePath ) );

		AbstractSpimData< ? > spimData = BioFormatsConvertFilesToSpimData.getSpimData( opener );
		List< ConverterSetup > converterSetups = new ArrayList<>();
		List< SourceAndConverter< ? > > sourceAndConverters = new ArrayList<>();
		BigDataViewer.initSetups( spimData, converterSetups, sourceAndConverters );

		if ( is2D )
		{
			List< SourceAndConverter< ? > > zCenteredSources = sourceAndConverters.stream().map( sac ->
			{
				AffineTransform3D sourceTransform = new AffineTransform3D();
				sac.getSpimSource().getSourceTransform( 0, 0, sourceTransform );
				double zTranslation = sourceTransform.get( 2, 3 );
				double zScale = sourceTransform.get( 2, 2 );
				AffineTransform3D centerZeroZTransform = new AffineTransform3D();
				centerZeroZTransform.translate( new double[]{ 0, 0, -zTranslation } );
				SourceAffineTransformer transformer = new SourceAffineTransformer( sac, centerZeroZTransform );
				return ( SourceAndConverter< ? > ) transformer.getSourceOut();
			} ).collect( Collectors.toList() );

			return zCenteredSources;
		}
		else
		{
			return sourceAndConverters;
		}
	}
}
```

If you have any ideas how to speed this up, let me know.
But don't sweat on it. It is ok in terms of speed.
In fact, I am now even more curious about memory consumption during this call `BigDataViewer.initSetups( spimData, converterSetups, sourceAndConverters );`

**Comment by NicoKiaru** [comment]
Ah! You can put several files in one BioFormatsBdvOpener  instead of a loop.

This could lead to a significant increase in speed and reduction in memory footprint ( to test ).

**Comment by tischi** [comment]
> Ah! You can put several files in one BioFormatsBdvOpener instead of a loop.
> This could lead to a significant increase in speed and reduction in memory footprint ( to test ).

I had a look at your code and to me it does not look like as if that should help. But if you insist I can test it ;-)

**Comment by NicoKiaru** [comment]
No I think you're right. What I had in mind does not work here. Don't bother

**Comment by NicoKiaru** [comment]
Regarding your initial questions in this thread : the memoization is supposed to increase the speed when re-opening of the file.

**Comment by joshmoore** [comment]
> Do you know whether one can tell BioFormats (Java API) not to create the *.bfmemo files?

`.bfmemo` files should only get created if a `Memoizer` has been actively added to the wrapper stack somewhere. i.e. https://github.com/BIOP/bigdataviewer-bioformats/search?q=Memoizer

**Comment by tischi** [comment]
@NicoKiaru 
Could we make this optional in the `OpenFilesWithBigdataviewerBioformatsBridgeCommand`?
If its hundreds of small files it may not help so much?
Also I am not sure everyone would appreciate having all those additional files in their folders.
But, I think it's low priority right now. If this is a lot of work to make it optional just leave it, I would say.

**Comment by NicoKiaru** [comment]
That should not be a lot of work. I'll make it as an option in the builder. But low priority indeed

**Comment by NicoKiaru** [comment]
I've done a few modification, the cool thing is that `Memoizer` now only appears once in the repo:

https://github.com/BIOP/bigdataviewer-bioformats/search?q=Memoizer

So that should be easy to make modular

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
