### ISSUE TITLE
xy offsets

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#3]
Given there is information about the xy stage position of an image in the metadata, are you taking this into consideration for the visualisation in Bdv?

**Comment by NicoKiaru** [comment]
It's done here:

https://github.com/BIOP/bigdataviewer-bioformats/blob/4e950c729538b3d6a4a455b3d10033aa4b74b83f/src/main/java/ch/epfl/biop/bdv/bioformats/BioFormatsHelper.java#L84-L115

Fall back to no metadata when nothing can be retrieved.

This function is called by the image loader, or by the open command if the flag `ignoremetadata` is set to false.
