### ISSUE TITLE
Check whether sources are 2D

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#32]
@NicoKiaru 
Is there a computationally cheap way to find out if the sources are 2D, within below code?
```
		AbstractSpimData< ? > spimData = BioFormatsConvertFilesToSpimData.getSpimData( opener );
		List< ConverterSetup > converterSetups = new ArrayList<>();
		List< SourceAndConverter< ? > > sourceAndConverters = new ArrayList<>();
		BigDataViewer.initSetups( spimData, converterSetups, sourceAndConverters );
```
I am a bit afraid to access the `RandomAcessibleInterval` inside of the `Source`s as this may trigger Bio-formats actually reading (quite) some data from disk. Is there another way?

**Comment by NicoKiaru** [comment]
Hmm, if you assume `sourceAndConverter.getSpimSource` is of class `BioFormatsBdvSource` then you can get the reader from the readerpool : https://github.com/BIOP/bigdataviewer-bioformats/blob/2930062511b89dcf5d93ad9b84a734d5bc6109fb/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvSource.java#L254

From the readerPool, you can get a reader for following this pattern:

```
IFormatReader reader = readerPool.acquire();
// use the reader as you want
readerPool.recycle(reader); // NEVER FORGET THIS LINE when you're done with the reader
```

And from the reader there's a way to get the z dimension

But it's not general because you need a casting - and you should not read anything by asking the RAI because it's cached, isn't it ?

**Comment by tischi** [comment]
> and you should not read anything by asking the RAI because it's cached, isn't it ?

Yeees, buuut ;-)
...do you know whether it is accessed already once anyway by any of those lines of code?

```
AbstractSpimData< ? > spimData = BioFormatsConvertFilesToSpimData.getSpimData( opener );
List< ConverterSetup > converterSetups = new ArrayList<>();
List< SourceAndConverter< ? > > sourceAndConverters = new ArrayList<>();
BigDataViewer.initSetups( spimData, converterSetups, sourceAndConverters );
```
If so, then I agree and then this is the best option.

**Comment by NicoKiaru** [comment]
I don't think so. What takes a long of time is the `setId` function but that's an intrinsic Bioformats limitation - the parsing of the czi and these weird Strings is the time limiting factor I'd say

**Comment by NicoKiaru** [comment]
> I am a bit afraid to access the `RandomAcessibleInterval` inside of the `Source`s as this may trigger Bio-formats actually reading (quite) some data from disk. Is there another way?

In fact if you have the `opener` (because it's a parameter of `getSpimData`), you can probably do this:

```
final IFormatReader reader = opener.getNewReader();
final IMetadata omeMeta = (IMetadata) reader.getMetadataStore();
if (omeMeta.getPixelsSizeZ(cSerie).getNumberValue().intValue() == 1) {
// is 2d
} else {
// is 3d
}
reader.close();
```
And I guess `cSerie` is zero because you have only one image ?
It's pure bioformats, so it won't read anything

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
