### ISSUE TITLE
Menu entries

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#33]
@NicoKiaru 
In version `0.2.10` it appears like this:

![image](https://user-images.githubusercontent.com/2157566/99972138-72db7600-2d9e-11eb-80b9-f033742327da.png)

Could we please change it to a normal Plugins menu entry "in this version", i.e. a version that is compatible with the current Fiji? Maybe you could release a version `0.2.10.1` just for this sake?

**Comment by NicoKiaru** [comment]
ahhhh damned!

I'll see what I can do

**Comment by NicoKiaru** [comment]
Ok, done starting from version 0.2.12
