### ISSUE TITLE
OME dependencies

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#34]
@NicoKiaru 

Do you know whether we need special OME dependencies? Or are the ones with the current Fiji OK?

![image](https://user-images.githubusercontent.com/2157566/101175647-b4450e80-3645-11eb-885d-541a38019c24.png)

**Comment by NicoKiaru** [comment]
The ones in FIJI should be ok. At least I never had any issue related to version mismatch and I never uploaded something specific from ome into an update site

**Comment by tischi** [comment]
Cool! Same for me!
