### ISSUE TITLE
multi-resolution tiled ome.tiff

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#35]
@NicoKiaru 
Can one open a multi-resolution tiled ome.tiff in bdv-bf?
And would you have an example file?
cc @joshmoore

**Comment by NicoKiaru** [comment]
No reason you can't?

Samples : https://docs.openmicroscopy.org/ome-model/5.6.3/ome-tiff/data.html

Waht do you mean by tiled ?

**Comment by tischi** [comment]
> What do you mean by tiled ?

https://iipimage.sourceforge.io/documentation/images/

In fact, I am not 100% sure how this is technically exactly implemented within a Tiff file, as I have never looked into one that had such "tiles". I guess the point is to have Tiff implement a 2D "Google Map" source (like you would need for slide scanner data).

I am asking here, because I never worked with such Tiff files. Do you have any experience?

**Comment by NicoKiaru** [comment]
@romainGuiet wrote this plugin https://github.com/BIOP/ijp-kheops that transforms files into a multi resoltution (or pyramidal) ome-tiff. We need this when the image is too big. Then bioformats can read this multiresolution source. So this works with bdv-bf, yes. But our most common use case is qupath. Both bdv-bf (with bdv-playground) and qupath handle correctly multiresolution sources for display. It's really important for interactivity.

But I'm confused. Do you mean tiled or pyramidal ? or both ? an image being tiled is independent from being pyramidal. (And pyramidal is, at least for me, equivalent to being 'multi-resolution'.)

**Comment by joshmoore** [comment]
In general, for google-map-iness you want both: tiled (chunked in higher D) and multi-resolution.

> Both bdv-bf (with bdv-playground) and qupath handle correctly multiresolution sources for display. It's really important for interactivity.

@NicoKiaru, so my read of this is yes (but I guess holler if there's anything that you know is suboptimal in the 2D case)

**Comment by tischi** [comment]
@romainGuiet 
Are you consciously writing tiles (aka xy chunks) into the pyramidal tiffs?

**Comment by romainGuiet** [comment]
Hi @tischi , 
I'm consciously calling [``converter.testConvert(new ImageWriter(), params) `` ](https://github.com/BIOP/ijp-kheops/blob/75d668acfb4336cfe7704d7ab110947e4eb64147/src/main/java/ch/epfl/biop/ij2command/KheopsMainCommand.java#L84)with the define params and the magic happen !

**Comment by tischi** [comment]
@NicoKiaru 
Here are the tiles:
```
            String[] params = {input_path.toString(), output_path.toString(),
                    "-pyramid-resolutions", String.valueOf(pyramidResolution),
                    "-pyramid-scale", String.valueOf(pyramidScale),
                    "-tilex", String.valueOf(tileSize),
                    "-tiley", String.valueOf(tileSize),
                    "-noflat",
```

**Comment by NicoKiaru** [comment]
@tischi opening a tiled ome.tiff is not a problem as far as I've tested, so I close the issue
