### ISSUE TITLE
Performance logging

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#36]
@NicoKiaru 

For debugging, teaching and benchmarking I think it would be great if one could add optional logging to the `CellLoaders`.
My idea is that in the user interface one could set a Logging Level to Debug (or Benchmark) and then would get such information: https://github.com/imglib/imglib2-cache/issues/16

What do you think?

**Comment by NicoKiaru** [comment]
Never done that, but why not ? Are you sure it does not impact performance when off ?

**Comment by tischi** [comment]
I think there is so much code in the loaders that one 
`if ( Logger.Level.equals ( Level.Debug ) )`
should not matter.

If you like the idea I think it could be already very interesting for the NEUBIAS seminar, because this would nicely demonstrate how you lazy load from big files.

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
