### ISSUE TITLE
Voxel size when loading

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#39]
@NicoKiaru 

Could you please remind me what this was?

```
BioFormatsBdvOpener
.positionReferenceFrameLength( new Length( 1, UNITS.MICROMETER ) ) // Compulsory
.voxSizeReferenceFrameLength( new Length( 100, UNITS.MICROMETER ) );
```

Probably related:

When I do this:

```
run("MRI Stack");
saveAs("Tiff", "/Users/tischer/Desktop/mri-stack.tif");
```

And then open this with BDP2 [ Open > Open Bio-Formats ], I get:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/2157566/117626203-254d9c80-b177-11eb-9e77-63cd8e80e7b2.png">

I think units of 1 pixel would be correct, wouldn't it?

**Comment by NicoKiaru** [comment]
Can't `mri-stack` be properly calibrated with a meaningful pixel size ?

Reference frame sometimes shows in bioformats library, I guess when nothing is known from metadata.

Internally in this library, we need to convert from one unit to another, it's quite deeply buried everywhere in this library ( helps with the positioning of tiles).

If the unit is 'pixel', there's no way bioformats can convert from pixel to any unit. So, I put a default physical value for the unit.

It's the 'null exception' of image analysis ;-). Null is convenient, but creates tons of issues.

**Comment by tischi** [comment]
Ok, but can I then set the _default_ length to 1 um?
`.voxSizeReferenceFrameLength( new Length( 1, UNITS.MICROMETER ) );`

**Comment by NicoKiaru** [comment]
Yep!

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
