### ISSUE TITLE
Image positions

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#6]
I discussed with a colleague and it seems that the positions in the metadata are often positions  of the image centre rather than the upper left corner. That means one would have to change the code where the `Transforms` are computed to take into account the image size; something like:

```
translation = image_centre - image_size / 2
```
 

 Would you be ok with me trying to implement such a modification?

**Comment by NicoKiaru** [comment]
Hum how sure/standard is that ?
In our case we have slide scanner data with multiple scans at multiple resolutions and it works nicely with the current implementation: https://www.youtube.com/watch?v=tuiaEXmFVyE.

This shows low res overview + high res locations. The overlay fits. If we do this change, I'm pretty sure it will not work anymore. Now if you have for sure some data where the position is specified from the image center, then we need to add this as an option, but not implement it like that by default.

**Comment by NicoKiaru** [comment]
In the metadata description from BioFormats, the plane position (https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Plane_PositionX) is defined as 
> The X position of the stage. Units are set by PositionXUnit.

So in the case of a tiling, it's not telling whether it's the center or the corner.
I know for sure that the 'corner case' occur (see above). So if you find a case where the 'center case' occur, then one need to add this as an option. 

Then one need to add the 'corner/center flag' to this function : https://github.com/BIOP/bigdataviewer-bioformats/blob/4e950c729538b3d6a4a455b3d10033aa4b74b83f/src/main/java/ch/epfl/biop/bdv/bioformats/BioFormatsHelper.java#L84-L115

that's the main function thing to change 
+ add this as a parameter in the `BioFormatsBdvSource` constructor
+ add a way to set/store this flag in the loader
+ add a parameter in the plugin

At some point the `BioFormatsBdvSource` class will have too many parameters in the constructor -> we will need to make a `BioFormatsBdvSourceBuilder`

**Comment by NicoKiaru** [comment]
Using the builder pattern 

https://github.com/BIOP/bigdataviewer-bioformats/blob/f3975db802b30a81b41efa41c6777f79a7b300dc/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L128-L136

and  your implementation,

https://github.com/BIOP/bigdataviewer-bioformats/blob/f3975db802b30a81b41efa41c6777f79a7b300dc/src/main/java/ch/epfl/biop/bdv/bioformats/BioFormatsMetaDataHelper.java#L124-L129

 the repo can now open the file on both ways.

The builder also contains an `auto()` method which can be modified to automatically set the convention based on the file format

https://github.com/BIOP/bigdataviewer-bioformats/blob/f3975db802b30a81b41efa41c6777f79a7b300dc/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java#L60-L91
