### ISSUE TITLE
Too many constructor parameters

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#7]
For me, it works quite well to have a settings class, e.g.

- https://github.com/tischi/fiji-plugin-morphometry/blob/master/src/main/java/de/embl/cba/morphometry/spindle/SpindleMorphometry.java#L84
- https://github.com/tischi/fiji-plugin-morphometry/blob/master/src/main/java/de/embl/cba/morphometry/spindle/SpindleMorphometrySettings.java#L10

Would that be an option for you? I could do it.

**Comment by NicoKiaru** [comment]
That could be an option, but the builder pattern is nicer to read:

https://dzone.com/articles/design-patterns-the-builder-pattern

I'll do it during after merging your PR.

**Comment by NicoKiaru** [comment]
So there is now a builder class for the opening of files :

https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvOpener.java

It's called like this:

https://github.com/BIOP/bigdataviewer-bioformats/blob/f3975db802b30a81b41efa41c6777f79a7b300dc/src/test/java/explore/OpenAndDisplayImageWithSource.java#L28-L43

Using the various methods you can set the way the file should be opened (center / corner convention + units + etc.)

What's supercool is that this class can be serialized. So the settings for opening the files can be stored in a readable format easily:
https://github.com/BIOP/bigdataviewer-bioformats/blob/f3975db802b30a81b41efa41c6777f79a7b300dc/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/XmlIoBioFormatsImgLoader.java#L35

And retrieved as well:

https://github.com/BIOP/bigdataviewer-bioformats/blob/f3975db802b30a81b41efa41c6777f79a7b300dc/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/XmlIoBioFormatsImgLoader.java#L57
